image: fedora:26
stages:
  - build
  - test
  - print_error

before_script:
  - dnf install -y gcc meson ninja-build gettext gtk-doc glib2-devel

# Job: build
build-libgwords:
  stage: build
  script:
  - ./configure
  - make

# Job: test
test-libgwords:
  stage: test
  script:
  - make check

error-libgwords:
  stage: print_error
  script:
  - cat _build/meson-logs/testlog.txt
  when: on_failure